name: treeved
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.4
  http: ^0.13.4
  link_preview_generator: ^1.2.0
  provider: ^6.0.2
  flutter_markdown: ^0.6.10
  velocity_x: ^3.3.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
